name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  mandatory-check:
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build
        run: |
          echo "Running build..."
          # Add your actual build commands here
          # Example: make build or npm install && npm run build
          echo "Build passed ✅"
