name: Sync repo → Azure Storage (after PR merge)

on:
  push:
    branches: [ main ]     # runs when a PR is merged to main
  workflow_dispatch:
    inputs:
      pr_number:
        description: "Enter a PR number to re-run sync"
        required: true
        type: string
permissions:
  contents: read

jobs:
  sync-nprd:
    runs-on: ubuntu-latest
    environment: nprd
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Override with PR commit
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "Fetching merge commit for PR #${{ inputs.pr_number }}"
          pr_commit=$(gh pr view ${{ inputs.pr_number }} --json mergeCommit --jq '.mergeCommit.oid')
          if [ -z "$pr_commit" ]; then
            echo "Could not find merge commit for PR #${{ inputs.pr_number }}"
            exit 1
          fi
          echo "Merge commit for PR #${{ inputs.pr_number }} is: $pr_commit"
          git fetch origin $pr_commit
          git checkout $pr_commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Sync folder1 → container/prefix folder1/
        run: |              
               echo 'Hey there its in progress' 

                az storage blob sync \
                 --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
                 --container ${{ vars.AZURE_STORAGE_CONTAINER }} \
                 --source "./$folder" \
                 --include-pattern "*.txt" \
                 --exclude-pattern "latest_version.txt" \
                 --auth-mode login \
                 --delete-destination true
  sync-dev:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Sync folder1 → container/prefix folder1/
        run: |              
               echo 'Hey there its in progress' 

                az storage blob sync \
                 --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
                 --container ${{ vars.AZURE_STORAGE_CONTAINER }} \
                 --source "./$folder" \
                 --include-pattern "*.txt" \
                 --exclude-pattern "latest_version.txt" \
                 --auth-mode login \
                 --delete-destination true
             
