name: Sync repo → Azure Storage (after PR merge)

on:
  push:
    branches: [ main ]     # runs when a PR is merged to main

permissions:
  contents: read

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Ensure folders exist so 'sync' can delete remote when local is empty
      #- name: Ensure folders exist
      #  run: |
      #    mkdir -p folder1 folder2

      - name: Sync folder1 → container/prefix folder1/
        run: |
              mkdir filtered
              
              for dir in */ ; do
              folder=$(basename "$dir")

              # Skip hidden/system folders
               if [[ "$folder" == ".git" || "$folder" == ".github" ]]; then
                 continue
               fi
              
               mkdir -p "filtered/$folder"

               find "./$folder" -type f -name "*.txt" -exec cp --parents {} "filtered/$folder/" \;

               echo 'Hey there its in progress' 

                az storage blob sync \
                 --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
                 --container ${{ vars.AZURE_STORAGE_CONTAINER }} \
                 --source "./$folder" \
                 --destination "filtered/$folder" \
                 --auth-mode login \
                 --delete-destination true
               done
          

      #- name: Sync folder2 → container/prefix folder2/
      #  run: |
      #    az storage blob sync \
      #      --account-name ${{ vars.AZURE_STORAGE_ACCOUNT }} \
      #      --container ${{ vars.AZURE_STORAGE_CONTAINER }} \
      #      --source ./folder2 \
      #      --destination folder2 \
      #      --auth-mode login \
      #      --delete-destination true
